[package]
name = "sudoku-rs"
version = "0.1.0"
authors = ["Ziyang Li"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
serde_json = "1.0"
structopt = "0.3"
