[package]
name = "sudoku-rs"
version = "0.1.0"
authors = ["Ziyang Li"]
edition = "2018"
description = "Sudoku solving library & command line executables"

[dependencies]
rand = "0.7"
serde_json = "1.0"
structopt = "0.3"
